---
kind: pipeline
name: default

steps:
- name: build
  image: docker
  environment:
    DOCKER_PASSWORD:
      from_secret: DOCKER_PASSWORD
  commands:
  - export DOCKER_HOST=unix:///var/run/host.sock
  - if [[ $DRONE_TAG ]]; then export DOCKER_TAG=$DRONE_TAG; else export DOCKER_TAG=$DRONE_BUILD_NUMBER; fi
  - docker login -u 'robot$drone' -p $DOCKER_PASSWORD harbor.dsrd.libraries.psu.edu
  - docker build -t harbor.dsrd.libraries.psu.edu/library/matomo:$DOCKER_TAG .
  - docker tag harbor.dsrd.libraries.psu.edu/library/matomo:$DOCKER_TAG harbor.dsrd.libraries.psu.edu/library/matomo:latest
  - docker push harbor.dsrd.libraries.psu.edu/library/matomo$DOCKER_TAG'
  when:
    events: [ tags ]
    branches: [ master ]
  volumes:
  - name: docker-sock
    path: /var/run/host.sock

volumes:
- name: docker-sock
  host:
    path: /var/run/docker.sock
---
kind: signature
hmac: b9114b1331d20753af42bd0bb606b89e87a599750158453a462953130383f71c

...
