version: "3"

services:

  matomo:
    build: .
    restart: always
    volumes:
      - matomo:/var/www/html
    environment:

      HOST_ENV: ${HOST_ENV}

      # matomo mysl connection
      MATOMO_DATABASE_ADAPTER: ${MATOMO_DATABASE_ADAPTER}
      MATOMO_DATABASE_TYPE: ${MATOMO_DATABASE_TYPE}
      MATOMO_DATABASE_HOST: ${MATOMO_DATABASE_HOST}
      MATOMO_DATABASE_USERNAME: ${MATOMO_DATABASE_USERNAME}
      MATOMO_DATABASE_PASSWORD: ${MATOMO_DATABASE_PASSWORD}
      MATOMO_DATABASE_DBNAME: ${MATOMO_DATABASE_DBNAME}
      MATOMO_DATABASE_TABLES_PREFIX: ${MATOMO_DATABASE_TABLES_PREFIX}

      # matomo admin
      MATOMO_SUPERUSER_USERNAME: ${MATOMO_SUPERUSER_USERNAME}
      MATOMO_SUPERUSER_PASSWORD: ${MATOMO_SUPERUSER_PASSWORD}
      MATOMO_SUPERUSER_EMAIL: ${MATOMO_SUPERUSER_EMAIL}

      # matomo site info
      MATOMO_VERSION: ${MATOMO_VERSION}
      MATOMO_SITENAME: ${MATOMO_SITENAME}
      MATOMO_URL: ${MATOMO_URL}
      MATOMO_INDEX: ${MATOMO_INDEX}
      MATOMO_TIMEZONE: ${MATOMO_TIMEZONE}

      # matomo extra tools plugin
      MATOMO_DB_HOST: ${MATOMO_DATABASE_HOST}
      MATOMO_DB_USERNAME: ${MATOMO_DATABASE_USERNAME}
      MATOMO_DB_PASSWORD: ${MATOMO_DATABASE_PASSWORD}
      MATOMO_DB_NAME: ${MATOMO_DATABASE_DBNAME}

      MATOMO_FIRST_USER_NAME: ${MATOMO_SUPERUSER_USERNAME}
      MATOMO_FIRST_USER_PASSWORD: ${MATOMO_SUPERUSER_PASSWORD}
      MATOMO_FIRST_USER_EMAIL: ${MATOMO_SUPERUSER_EMAIL}

      MATOMO_FIRST_SITE_URL: http://localhost
      MATOMO_FIRST_SITE_NAME: ${MATOMO_SITENAME}
    ports:
      - "80:80"

  db:
    image: mariadb
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
    ports:
      - "3306:3306"

volumes:
  db-data:
  matomo:
